// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class ExplseleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }



  @Test
  public void explselenium() {
    driver.get("https://expletiveami.wordpress.com/");
    driver.manage().window().setSize(new Dimension(1908, 999));
    js.executeScript("window.scrollTo(0,1779)");
    driver.findElement(By.cssSelector("#post-314 p:nth-child(6)")).click();
    assertThat(driver.findElement(By.cssSelector("#post-314 p:nth-child(6)")).getText(), is("Seems I’ve already seen it.\\\\nSeems I’ve already heard it.\\\\nSeems I’ve already felt it.\\\\nSeems I’ve already tasted it.\\\\nAnd that’s why\\\\nUndoubtedly that’s why\\\\nI feel so good\\\\nAnd bad today."));
    driver.close();
  }
}
