// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import java.util.concurrent.TimeUnit;
import java.util.List;
import java.util.Arrays;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;


public class NewnewTest {

  private WebDriver driver; // объявила переменную драйвер и сказала что она будет Вебдрайвер
  private JavascriptExecutor js;
  public static final Dimension browserWindowSize = new Dimension(1280, 960);

  @Before
  public void setUp() {
      // Open browser
      driver = (WebDriver) new ChromeDriver();// инициализация

      // Driver as (casted to) JS executor
      js = (JavascriptExecutor) driver; // коробка
  }

  @After
  public void tearDown() {
      // Close browser and quit driver
      driver.close();
      driver.quit();
  }

  public void ensureWithDataCode(String datacode) {
      System.err.println("Clicking on element with data-code attribute: " + datacode);

      // Click Appearance menu
      driver.findElement(By.cssSelector("#box-apps-menu li[data-code=\"" + datacode + "\"] > a")).click();

      // Ensure that div.panel-heading exists
      driver.findElement(By.cssSelector("div.panel-heading"));
  }

  @Test
  public void newnew() {
      // Set implicit wait timeouts to 10 seconds
      driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

      // Get URL
      driver.get("http://demo.litecart.net/admin/login.php");

      // Set browser window size to specified dimension
      driver.manage().window().setSize(browserWindowSize);

      // Click Login button
      driver.findElement(By.xpath("//*[@id=\"box-login\"]/form/div[2]/button")).click();

      List<String> dataCodes = Arrays.asList("appearance",
              "template",
              "logotype",
              "catalog",
              "catalog",
              "attribute_groups",
              "option_groups",
              "manufacturers",
              "suppliers",
              "delivery_statuses",
              "sold_out_statuses",
              "quantity_units",
              "csv",
              "countries",
              "currencies",
              "customers",
              "customers",
              "newsletter",
              "geo_zones",
              "languages",
              "languages",
              "storage_encoding",
              "modules",
              "customer",
              "shipping",
              "payment",
              "order",
              "order_total",
              "jobs",
              "orders",
              "orders",
              "order_statuses",
              "pages",
              "pages",
              "csv",
              "reports",
              "monthly_sales",
              "most_sold_products",
              "settings",
              "store_info",
              "defaults",
              "email",
              "listings",
              "legal",
              "images",
              "checkout",
              "advanced",
              "security",
              "slides",
              "tax",
              "tax_rates",
              "tax_classes",
              "translations",
              "search",
              "scan",
              "csv",
              "users",
              "vqmods");

      for (String dc : dataCodes) {
          ensureWithDataCode(dc);
      }
  }

}
